```python
# 获取exception的错误原因
try:
	可能会产生多种异常代码
except 异常类型1:
	print(....)
except 异常类型2:
	pass
except Exception as err:   # Exception 所有异常的父类
	print(err)    # err 内容就是错误原因
```

```python
try:
	# 可能会产生异常代码
	pass
except:
    #有异常才会进入代码
    #except Exception as err:
    pass
else:
    #没有异常才会进入代码
    pass
finally:
   # 无论有没有异常都会执行的代码
   pass
```

